# Generated by Django 5.2.9 on 2025-12-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('logo_1', models.ImageField(blank=True, null=True, upload_to='setting_logo/logo_1')),
                ('logo_2', models.ImageField(blank=True, null=True, upload_to='setting_logo/logo_2')),
                ('transparent_logo', models.ImageField(blank=True, null=True, upload_to='site_setting/transparent_logo')),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
                'db_table': 'website_settings',
            },
        ),
    ]
