# Generated by Django 5.2.9 on 2025-12-05 18:17

import core.media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_gallery_image_alter_gallery_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.media_path.OverwriteStorage(), upload_to=core.media_path.get_gallery_upload_to),
        ),
    ]
