# Generated by Django 5.2.9 on 2025-12-05 18:18

import core.media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=1, storage=core.media_path.OverwriteStorage(), upload_to=core.media_path.get_gallery_upload_to),
            preserve_default=False,
        ),
    ]
