# Generated by Django 5.2.9 on 2025-12-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-created_at',), 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
    ]
