# Generated by Django 5.2.9 on 2026-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_favorite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
