# Generated by Django 5.2.9 on 2026-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_brand_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
