# Generated by Django 5.2.9 on 2025-12-14 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_otp_create_at_user_otp_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='لطفا شماره موبایل خود را به درستی وارد کنید.', regex='^09\\d{9}$')])),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'کد پستی شما باید دقیقاً 10 رقم باشد.')])),
                ('plaque', models.CharField(blank=True, max_length=10, null=True)),
                ('full_address', models.TextField()),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
