# Generated by Django 5.2.9 on 2025-12-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='title_en',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
