# Generated by Django 5.2.9 on 2025-12-22 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcategory_title_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogVisit',
            new_name='PostVisit',
        ),
    ]
