# Generated by Django 5.2.9 on 2025-12-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='final_price',
        ),
    ]
