# Generated by Django 5.2.9 on 2025-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitems_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'در انتظار پرداخت'), ('pending', 'پردازش و بسته بندی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده')], default='cart', max_length=10),
        ),
    ]
